#!/usr/bin/env python3
"""Hermetic release-contract gate for Gunbrick Reloaded.

The gate audits source, generated launcher, BYO recipe, release manifest and
the project-built Linux ELF. It never executes owner Android code.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys
import tempfile


PORT = Path(__file__).resolve().parents[1]
REPO = PORT.parents[1]
PUBLIC_ELF = PORT / "build" / "gunbrick-nextos"


def require(value: bool, message: str) -> None:
    if not value:
        raise AssertionError(message)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def no_duplicates(pairs):
    result = {}
    for key, value in pairs:
        require(key not in result, f"duplicate JSON key: {key}")
        result[key] = value
    return result


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"),
                      object_pairs_hook=no_duplicates)


def run(*argv: str, cwd: Path | None = None) -> str:
    result = subprocess.run(argv, cwd=cwd, text=True,
                            stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE, check=False)
    require(result.returncode == 0,
            f"{' '.join(argv)} failed ({result.returncode})\n"
            f"{result.stdout}\n{result.stderr}")
    return result.stdout


def check_launcher_and_contract() -> None:
    nxport = load_json(PORT / "nxport.json")
    require(nxport["schema_version"] == 2, "nxport schema drift")
    require(nxport["id"] == "gunbrick", "wrong port id")
    require(nxport["executable"] == "gunbrick-nextos",
            "noncanonical public executable")
    require(nxport["nxextract"] == {"mode": "yes", "version": "1.2.6"},
            "NXExtract contract drift")
    require(len(nxport["required_capabilities"]) ==
            len(set(nxport["required_capabilities"])),
            "duplicate capability")
    for capability in (
        "host.portmaster", "host.aarch64-libs", "graphics.window",
        "graphics.gles2", "graphics.egl", "graphics.egl-config",
        "graphics.drawable", "input.controller-mapping",
        "input.controller-api",
    ):
        require(capability in nxport["required_capabilities"],
                f"missing capability: {capability}")

    launcher = (PORT / "Gunbrick.sh").read_text(encoding="utf-8")
    require("generated by nxbootstrap 0.6.0" in launcher,
            "launcher is not nxbootstrap 0.6.0")
    for guarantee in ("flock -n 9", 'wait "$game_pid"',
                      "nxbootstrap_finish", "pm_finish"):
        require(guarantee in launcher,
                f"launcher guarantee missing: {guarantee}")
    for retired in ("nxbootstrap.sh", "nxbootstrap-0.5.1.sh",
                    "nxdeployment.json", "run.sh"):
        require(not (PORT / retired).exists(),
                f"retired launcher artifact remains: {retired}")

    generator = REPO / "framework/nxbootstrap/tools/generate-port.py"
    with tempfile.TemporaryDirectory(prefix="gunbrick-launcher-") as temp:
        run(sys.executable, str(generator), str(PORT / "nxport.json"),
            "--output", temp)
        generated = Path(temp) / "Gunbrick.sh"
        require(generated.read_bytes() == (PORT / "Gunbrick.sh").read_bytes(),
                "checked-in launcher is stale")


def check_owner_recipe() -> None:
    recipe = load_json(PORT / "extractor.json")
    require(recipe["schema"] == 1, "extractor schema drift")
    require(recipe["input"]["packages"] == ["com.nitrome.Gunbrick"],
            "package identity drift")
    require(recipe["hooks"] == [], "unexpected extraction hook")
    require(set(recipe["commit"]) == {"assets", "lib"},
            "transaction roots drift")

    expected = {
        "android-unity-assets": {
            "exact_files": 13,
            "exact_bytes": 114848937,
            "tree_fingerprint":
                "427bda5093c4d60bb01f3b39ab0b5e289716db8b56d9a7b98690521f0162ab07",
        },
        "android-native-loader": {
            "size": 6728,
            "sha256":
                "6c75c14ca2e3933c545bde758e2d6a009b5eed8d689d789a70ba2c7ef198b9b6",
        },
        "android-unity-player": {
            "size": 15846704,
            "sha256":
                "1a8b6025395e2ea5eb93a2eae2c0909f775e2730a449d690f79e8e2bd47f8c0e",
        },
        "android-il2cpp-runtime": {
            "size": 114824672,
            "sha256":
                "da0bc61dae55907028aa9ff8d47c77841b6821869935c933489b52384c93191e",
        },
    }
    for rule in recipe["extract"]:
        for key, value in expected[rule["id"]].items():
            require(rule["validate"].get(key) == value,
                    f"payload pin drift: {rule['id']} {key}")
    run(sys.executable, str(PORT / "nxextract/nxextract.py"),
        "recipe-check", "--recipe", str(PORT / "extractor.json"))

    status = load_json(PORT / "references/migration-status-v1.json")
    adapter = load_json(PORT / "references/adapter-contract-v1.json")
    require(status["physical_device_evidence"] is True,
            "physical validation receipt missing")
    require(status["release_blocker"]["active"] is False,
            "stale release blocker")
    require(adapter["physical_device_evidence"] is True and
            adapter["release_ready"] is True,
            "adapter is not release ready")


def check_source_policy() -> None:
    source = "\n".join(
        path.read_text(encoding="utf-8")
        for path in sorted((PORT / "src").glob("*.[ch]"))
    )
    for pattern in (
        r"UpdateLevelCompletion", r"Bomb[ _-]?Chicken", r"Hitman",
        r"SDL_VIDEODRIVER\s*=", r"SDL_AUDIODRIVER\s*=",
        r"GB_WATCHDOG", r"GB_SCREENSHOT", r"GB_FBO_CAPTURE",
    ):
        require(re.search(pattern, source, re.IGNORECASE) is None,
                f"foreign/debug token in source: {pattern}")
    require("nxloader_module_resolve(module->module, registry, 0, &report)"
            in source, "strict nxloader resolution changed")
    require("accepted_versions[] = { 0x00010006 }" in source,
            "JNI 1.6 allowlist changed")
    require("NXINPUT_CURSOR_OFF" in source,
            "debug cursor became active")

    main = (PORT / "src/main.c").read_text(encoding="utf-8")
    lifecycle = (
        "gb_load_modules()", "nx_run_init(main_mod)",
        "nx_call_jni_onload(main_mod", "NativeLoader.load completed",
        "run_unity()",
    )
    offsets = [main.index(token) for token in lifecycle]
    require(offsets == sorted(offsets), "native lifecycle order drift")


def check_public_elf() -> None:
    require(PUBLIC_ELF.is_file(), "public ELF missing")
    header = run("readelf", "-hW", str(PUBLIC_ELF))
    require("AArch64" in header, "public ELF is not AArch64")
    dynamic = run("readelf", "-dW", str(PUBLIC_ELF))
    require("(RPATH)" not in dynamic and "(RUNPATH)" not in dynamic,
            "public ELF contains RPATH/RUNPATH")
    program = run("readelf", "-lW", str(PUBLIC_ELF))
    require(not any("LOAD" in line and "RWE" in line
                    for line in program.splitlines()),
            "public ELF contains an RWE load segment")
    versions = run("readelf", "--version-info", str(PUBLIC_ELF))
    glibc = [(int(a), int(b)) for a, b in
             re.findall(r"GLIBC_(\d+)\.(\d+)", versions)]
    require(glibc and max(glibc) <= (2, 30),
            "public ELF exceeds GLIBC_2.30")
    needed = sorted(re.findall(r"Shared library: \[([^]]+)\]", dynamic))
    require(needed == sorted([
        "ld-linux-aarch64.so.1", "libSDL2-2.0.so.0", "libc.so.6",
        "libdl.so.2", "libgcc_s.so.1", "libm.so.6",
        "libpthread.so.0", "libz.so.1",
    ]), f"DT_NEEDED drift: {needed}")
    symbols = run("nm", "-D", str(PUBLIC_ELF))
    for symbol in ("nxloader_module_resolve", "nxcompat_probe",
                   "nxinput_create", "nxaudio_classify_backend"):
        require(re.search(rf"\b{symbol}$", symbols, re.MULTILINE) is not None,
                f"framework symbol missing: {symbol}")


def check_release_and_privacy() -> None:
    release = load_json(PORT / "nxrelease.json")
    package = release["package"]
    require(package["version"] == "0.2.0", "release version drift")
    require(package["launcher_contract"]["version"] == "0.6.0",
            "bootstrap version drift")
    require(package["launcher_contract"]["config_sha256"] ==
            sha256(PORT / "nxport.json"), "nxport pin stale")
    require(release["nxextract"]["recipe_sha256"] ==
            sha256(PORT / "extractor.json"), "extractor pin stale")
    for entry in release["files"]:
        source = PORT / entry["source"]
        require(source.is_file() and not source.is_symlink(),
                f"release source missing/unsafe: {entry['source']}")
        require(entry["sha256"] == sha256(source),
                f"release pin stale: {entry['source']}")
        require(not re.search(r"\.(apk|apkm|apks|xapk|obb|so)$",
                              entry["target"], re.IGNORECASE),
                f"owner data entered release: {entry['target']}")

    public_text = "\n".join(
        path.read_text(encoding="utf-8", errors="strict")
        for path in PORT.rglob("*")
        if path.is_file() and path.suffix in {".md", ".txt", ".json", ".sh"}
        and not any(part in {"gamedata", "stage", "verify", ".build",
                             "tests", "build"}
                    for part in path.relative_to(PORT).parts)
    )
    for pattern in (r"192\.168\.", r"/home/", r"root@"):
        require(re.search(pattern, public_text, re.IGNORECASE) is None,
                f"private literal in release text: {pattern}")


def main() -> int:
    check_launcher_and_contract()
    check_owner_recipe()
    check_source_policy()
    check_public_elf()
    check_release_and_privacy()
    print("GUNBRICK RELEASE CONTRACT: PASS")
    print("physical_device_evidence=1 proprietary_payload_packaged=0")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
